import { Inter } from "next/font/google";
import { Oswald } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import NavbarComponent from "@/components/navbar/Navbar";


// const inter = Inter({ subsets: ["latin"] });
const oswald = Oswald({
  subsets:["latin"],
  weight:["300", "400", "500", "700", "600"],
  variable: "— font-oswald" ,
  })

export const metadata = {
  title: "Ashwani xports",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <NavbarComponent />
        {children}
        <Footer />
      </body>
    </html>
  );
}
